[phases.install]
cmds = [
  'echo "=========================================================="',
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@9.15.5 --active",
  "pnpm install"
]